### PR TITLE
Timestamp validation

### PR DESCRIPTION
**Pull request by alibori**
Hi!

Regarding [Issue #3](https://github.com/tempestphp/tempest-framework/issues/3) this PR add Timestamp validation rule and it's tests.

Let  me know if something must to be changed.

Thanks!

### CODE REVIEW

**Comment by aidan-casey** [comment]
Thanks, @alibori! I've added some notes if you don't mind reviewing. 🙂

**Comment by alibori** [comment]
Hi @aidan-casey !

Whre are these notes? I can't find it 😅 

I'll review it with pleasure.

Thanks!

**Comment by aidan-casey** [comment]
@alibori - Do you see them now?

**Comment by aidan-casey** [comment]
@alibori - Can you just run `composer qa` and commit the results? I should be able to merge this then.

Thanks!

**Comment by alibori** [comment]
@aidan-casey Sure, it's done now.

Thanks!

**Pull request merged**
