### PR TITLE
DRAFT: Refactor reflection helpers.

### PR DESCRIPTION
**Pull request by aidan-casey**

### CODE REVIEW

**Comment by aidan-casey** [comment]
@brendt - Are you good with this general direction before I proceed?

**Comment by brendt** [comment]
Yes, for sure! As I mentioned in the other PR though: I'd like to avoid huge PRs at this stage. So if possible, let's merge this ASAP (just the namespace move and composer setup), and then do whatever finetuning you want in another PR

**Comment by aidan-casey** [comment]
I'll merge this after #377.

**Comment by brendt** [comment]
@aidan-casey #377 is merged :)

**Comment by aidan-casey** [comment]
Closing in favor of #382 😛

**Pull request closed without merging**
