### PR TITLE
Added PHPAT

### PR DESCRIPTION
**Pull request by Plytas**
Couldn't resist and added [PHPAT](https://www.phpat.dev/) as an alternative to Pest for architecture tests. This should be compared to #141

### CODE REVIEW

**Comment by Plytas** [comment]
I can take care of this.

**Comment by aidan-casey** [comment]
Thank you, @Plytas!

**Comment by Plytas** [comment]
@aidan-casey I opened #169 in order to reduce the amount of changes in this PR.

**Comment by aidan-casey** [comment]
Love it. Thank you!

**Comment by Plytas** [comment]
@aidan-casey @brendt this should be up to date and passing with initial validation rules.

**Pull request merged**
