### PR TITLE
Adds ElseIfAttribute feature

### PR DESCRIPTION
**Pull request by yassiNebeL**

### CODE REVIEW

**Comment by brendt** [comment]
There are a lot of things missing from this PR:

- Tests
- Support for `elseif` in the `else` attribute
- Support for `elseif` after an `if` attribute

**Comment by yassiNebeL** [comment]
I’m looking for a method that can help me to determine if a given statement was ok or wasn’t, in order to know if I should return an element or not

Thank you in advance!

**Comment by brendt** [comment]
> I’m looking for a method that can help me to determine if a given statement was ok or wasn’t, in order to know if I should return an element or not

I'm not sure I fully understand? You might need to add a public method in `IfAttribute` and `IfElseAttribute` to determine whether their condition is matched or not.

**Comment by brendt** [comment]
Gonna work on this some more in a separate branch

**Pull request merged**
