### PR TITLE
feat: add json validation rule

### PR DESCRIPTION
**Pull request by vsergiu93**
I know is not in the list, but I think it might be useful to have it. 

Also it might look ugly, but wanted to use the new function json_validate, maybe instead of adding this polyfill I could just move the body of the function inside the isValid method.

### CODE REVIEW

**Comment by vsergiu93** [comment]
@aidan-casey Do you think it would be useful to add [php 8.3 to phpunit action](https://github.com/tempestphp/tempest-framework/blob/main/.github/workflows/quality-control.yml#L65)?

**Comment by aidan-casey** [comment]
Thanks for the PR, @vsergiu93! I actually meant to add this one to the list.

Let me sit on this implementation for a day. I was just speaking with @brendt about bumping the Tempest PHP version (because we can!) to 8.3 anyway.

As far as adding 8.3 to the matrix, I think that's an awesome idea! I would merge a PR for that.

**Comment by vsergiu93** [comment]
Sure, just let me know if you want to change something. 

Thanks

**Comment by aidan-casey** [comment]
@vsergiu93 - Go ahead and convert this to entirely `json_validate`. We will be bumping the PHP dependency. 🙂

**Comment by vsergiu93** [comment]
@aidan-casey Done :)

**Comment by aidan-casey** [comment]
Love it! Thank you.

**Pull request merged**
