### PR TITLE
Refactor tests to `Unit` namespace

### PR DESCRIPTION
**Pull request by Plytas**
In preparation for #151

### CODE REVIEW

**Comment by aidan-casey** [comment]
@Plytas - do you have an easy way to optimize imports here? Would rather import the classes than use the FQDN.

**Comment by Plytas** [comment]
I just used PhpStorm to move files. I see now where it failed to import. Will fix that.

**Comment by Plytas** [comment]
@aidan-casey should be imported now.

@brendt can pass feedback to JetBrains :D
When moving classes it didn't properly import (or even provide an option to import via context menu) these cases. It seems to be related to using classes from the same namespace as they are not imported by default.
image

**Comment by aidan-casey** [comment]
That's alright it gives me a good reason to add a CS-Fixer rule. 😉

**Comment by aidan-casey** [comment]
Thank you for all your work here, @Plytas!

**Comment by Plytas** [comment]
My pleasure! 🫡

**Pull request merged**
