### PR TITLE
test(console): add test for install command

### LINKED ISSUE #420: Missing unit test for install command
### Tempest Version

1.0-alpha1

### PHP Version

8.3

### Operating System

MacOS

### Description

/

### Steps to Reproduce

/

### PR DESCRIPTION
**Pull request by kapersoft**
Closes #420

### CODE REVIEW

**Comment by aidan-casey** [comment]
Thanks for the PR, @kapersoft! Can you just take a look at why the tests are failing on Windows?

**Comment by aidan-casey** [comment]
@kapersoft - The issue here is likely with the `/tmp` directory. Because of the need for cross platform to support the Windows tests, you might be better off using `sys_get_temp_dir()`. 🙂

**Comment by kapersoft** [comment]
@aidan-casey The `/tmp`-directory is not the issue. There are two other issues: 
- The `PathHelper` does not replace `/`-separators
- The `InstallCommand` does not use the `PathHelper`. So the displayed path is a mix of Windows and Unix directory separators. (see [test output](https://github.com/tempestphp/tempest-framework/actions/runs/10931332002/job/30346107238?pr=432#step:10:54))

I think I have fixed both now :)

**Comment by aidan-casey** [comment]
Hey @kapersoft! Looks like some tests are still failing on Windows. Do you want me to take a look at this?

**Comment by kapersoft** [comment]
@aidan-casey I have updated the PathHelper to support Windows paths. I have included a test as proof. Let me know if this is the way you want to handle Windows support.

The test for InstallCommand and PathHelper runs locally on Windows and Mac without any issues.

**Comment by brendt** [comment]
Looks good, the failing tests have nothing to do with this PR, so I'm going to merge 👍

**Comment by brendt** [comment]
Thanks btw @kapersoft !

**Pull request merged**
